// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'dart:typed_data' as i2;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    teams,
    matchResults,
    pitScouting,
  ];
  late final Shape0 teams = Shape0(
    source: i0.VersionedTable(
      entityName: 'teams',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(team_number, event_code, game_format)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 matchResults = Shape1(
    source: i0.VersionedTable(
      entityName: 'match_results',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(uuid)'],
      columns: [
        _column_4,
        _column_1,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_2,
        _column_9,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 pitScouting = Shape2(
    source: i0.VersionedTable(
      entityName: 'pit_scouting',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(team_number, event_code, game_format)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_7,
        _column_8,
        _column_9,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get teamNumber =>
      columnsByName['team_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get eventCode =>
      columnsByName['event_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get gameFormat =>
      columnsByName['game_format']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pickListPosition =>
      columnsByName['pick_list_position']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'team_number',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'event_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'game_format',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pick_list_position',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<BigInt> get uuid =>
      columnsByName['uuid']! as i1.GeneratedColumn<BigInt>;
  i1.GeneratedColumn<String> get eventCode =>
      columnsByName['event_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get teamNumber =>
      columnsByName['team_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get matchNumber =>
      columnsByName['match_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<BigInt> get timeStamp =>
      columnsByName['time_stamp']! as i1.GeneratedColumn<BigInt>;
  i1.GeneratedColumn<String> get scoutName =>
      columnsByName['scout_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get gameFormat =>
      columnsByName['game_format']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get data =>
      columnsByName['data']! as i1.GeneratedColumn<i2.Uint8List>;
}

i1.GeneratedColumn<BigInt> _column_4(String aliasedName) =>
    i1.GeneratedColumn<BigInt>(
      'uuid',
      aliasedName,
      false,
      type: i1.DriftSqlType.bigInt,
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'team_number',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'match_number',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<BigInt> _column_7(String aliasedName) =>
    i1.GeneratedColumn<BigInt>(
      'time_stamp',
      aliasedName,
      false,
      type: i1.DriftSqlType.bigInt,
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scout_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<i2.Uint8List> _column_9(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'data',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get teamNumber =>
      columnsByName['team_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get eventCode =>
      columnsByName['event_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get gameFormat =>
      columnsByName['game_format']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<BigInt> get timeStamp =>
      columnsByName['time_stamp']! as i1.GeneratedColumn<BigInt>;
  i1.GeneratedColumn<String> get scoutName =>
      columnsByName['scout_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get data =>
      columnsByName['data']! as i1.GeneratedColumn<i2.Uint8List>;
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
